#!/usr/bin/env bash

ln -sf ~/.cache/wal/picom.conf ~/.config/picom/picom.conf
ln -sf ~/.cache/wal/dunstrc ~/.config/dunst/dunstrc

pkill dunst; setsid -f dunst

notify-send "wallpaper and colorscheme changed; setting rgb value"

sudo openrgb --noautoconnect -c $(tail -c +2 ~/.cache/wal/rgb) -b 65 # set rgb last so it doesn't hang
